### ISSUE TITLE
bodaUndefined_v18.17.0.node: invalid ELF header

### ISSUE THREAD

**Issue by wAnFen1017** [xuxiaobo-bobo/boda_jsEnv#8]
Error: /home/wanfen/work/ZL/c3/ZLCollector_v3/Downloader/spiders/request/rs/framework/node_plugin/bodaUndefined_v18.17.0.node: invalid ELF header

在Ubuntu下运行报错，使用的node是官方18.19.1版本，经测试windows下正常。

**Comment by xuxiaobo-bobo** [comment]
bodaUndefined_v18.17.0.node 这个node插件只能在windows系统下运行
